import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() => runApp(const NavArApp());

class NavArApp extends StatelessWidget {
  const NavArApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'NavAR',theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:const Color(0xFF0F1020),colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFFF4B4B),brightness:Brightness.dark)),home:const HomePage());
}
class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage> {
 final map=MapController(); final search=TextEditingController(); LatLng center=const LatLng(55.7558,37.6173); bool dark=true; int tab=0;
 @override Widget build(BuildContext context){
  if(tab==1)return Scaffold(body:_transit(),bottomNavigationBar:_nav()); if(tab==2)return Scaffold(body:_ar(),bottomNavigationBar:_nav());
  return Scaffold(body:Stack(children:[FlutterMap(mapController:map,options:MapOptions(initialCenter:center,initialZoom:14),children:[TileLayer(urlTemplate:dark?'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png':'https://tile.openstreetmap.org/{z}/{x}/{y}.png',subdomains:const['a','b','c','d']),MarkerLayer(markers:[Marker(point:center,width:28,height:28,child:Container(decoration:BoxDecoration(shape:BoxShape.circle,color:const Color(0xFFFF4B4B),border:Border.all(color:Colors.white,width:3))))])]),SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:Material(color:const Color(0xFF242436),borderRadius:BorderRadius.circular(16),child:TextField(controller:search,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Поиск мест, адресов...',border:InputBorder.none,contentPadding:EdgeInsets.all(16))))),Positioned(right:16,bottom:100,child:Column(children:[FloatingActionButton.small(heroTag:'theme',onPressed:()=>setState(()=>dark=!dark),child:Icon(dark?Icons.light_mode:Icons.dark_mode)),const SizedBox(height:10),FloatingActionButton.small(heroTag:'ar',onPressed:()=>setState(()=>tab=2),child:const Icon(Icons.navigation))])),Positioned(left:16,right:16,bottom:12,child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF242436),borderRadius:BorderRadius.circular(22)),child:Row(children:[Expanded(child:_action(Icons.route,'Маршрут')),Expanded(child:_action(Icons.directions_transit,'Транспорт')),Expanded(child:_action(Icons.bookmark,'Места'))])))]),bottomNavigationBar:_nav());
 }
 Widget _action(IconData icon,String text)=>InkWell(onTap:()=>setState(()=>tab=text=='Транспорт'?1:0),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(icon,color:const Color(0xFFFF4B4B)),const SizedBox(height:4),Text(text,style:const TextStyle(fontSize:11))]));
 Widget _nav()=>NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.map),label:'Карта'),NavigationDestination(icon:Icon(Icons.directions_transit),label:'Транспорт'),NavigationDestination(icon:Icon(Icons.navigation),label:'AR')]);
 Widget _field(IconData i,String t)=>Container(height:50,padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:const Color(0xFF242436),borderRadius:BorderRadius.circular(12)),child:Row(children:[Icon(i,color:const Color(0xFFFF4B4B)),const SizedBox(width:10),Text(t,style:const TextStyle(color:Colors.white70))]));
 Widget _transit()=>SafeArea(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Общественный транспорт',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:18),_field(Icons.radio_button_checked,'Откуда'),const SizedBox(height:8),_field(Icons.location_on,'Куда'),const SizedBox(height:14),FilledButton.icon(onPressed:(){},icon:const Icon(Icons.route),label:const Text('Построить маршрут')),const SizedBox(height:20),const ListTile(leading:Icon(Icons.subway),title:Text('Метро'),subtitle:Text('12 мин · 1 пересадка')),const ListTile(leading:Icon(Icons.directions_bus),title:Text('Автобус'),subtitle:Text('18 мин · без пересадок'))])));
 Widget _ar()=>Stack(children:[Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF080914),Color(0xFF20233D),Color(0xFF080914)],begin:Alignment.topCenter,end:Alignment.bottomCenter))),Center(child:Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(24)),child:const Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.turn_right,color:Color(0xFFFF4B4B),size:64),SizedBox(height:8),Text('Поверните направо',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),Text('через 120 м',style:TextStyle(color:Colors.white70))]))),SafeArea(child:Align(alignment:Alignment.bottomCenter,child:Padding(padding:const EdgeInsets.all(16),child:FilledButton.icon(onPressed:()=>setState(()=>tab=0),icon:const Icon(Icons.map),label:const Text('Вернуться к карте'))))) ]);
}
